import java.util.ArrayList;

/*
 * The DataGroup Class is used to consolidate all of the data generated by the glove hardware
 * (Acceleration, Jerk, Angle, and Pressures 1-19) into one variable
 */


	/*  |-------------Pressures Map-------------|
		|1.Pointer Top							|
		|2.Pointer Middle						|
		|3.Pointer Bottom						|
		|4.Long Top								|
		|5.Long Middle							|
		|6.Long Bottom							|
		|7.Ring Top								|
		|8.Ring Middle							|
		|9.Ring Bottom							|
		|10.Short Top							|
		|11.Short Middle						|
		|12.Short Bottom						|
		|13. Thumb Top							|
		|14. Thumb Bottom						|
		|15.Lateral Distal Palmer Crease		|
		|16.Medial Distal Palmer Crease			|
		|17.Medial Proximal Palmer Crease		|
		|18.Hypothenar Eminence		            |
		|19.Palmaris Brevis	                	|
		|---------------------------------------|

		*/

public class DataGroup {

	private ArrayList<Double> Accelerations = new ArrayList<Double>();								
	private ArrayList<Double> Jerks = new ArrayList<Double>();
	private ArrayList<Double> Angles = new ArrayList<Double>();
	private ArrayList<ArrayList<Double>> Pressures= new ArrayList<ArrayList<Double>>();
	private ArrayList<Double> Times = new ArrayList<Double>();
	
	
	public DataGroup(){
		
	}
	
	public void setTimes(ArrayList<Double> NewTimes){
		
		Times.clear();
		Times.addAll(NewTimes);
	}
	
	
	public void setAccelerations(ArrayList<Double> NewAccelerations){
		
		Accelerations.clear();
		Accelerations.addAll(NewAccelerations);
	}
	
	public void setJerks(ArrayList<Double> NewJerks){
		Jerks.clear();
		Jerks.addAll(NewJerks);
	}
	public void setAngles(ArrayList<Double> NewAngles){
		Angles.clear();
		Angles.addAll(NewAngles);
	}
	public void setPressures(ArrayList<ArrayList<Double>> NewPressures){
		Pressures.clear();
		Pressures.addAll(NewPressures);
	}

public ArrayList<Double> getTimes(){
		
		
		return Times;
	}
	
	public ArrayList<Double> getAccelerations(){
		
		
		return Accelerations;
	}
	
	public ArrayList<Double> getJerks(){
		
		return Jerks;
	}
	public ArrayList<Double> getAngles(){
		
		return Angles;
	}
	public ArrayList<ArrayList<Double>> getPressures(){
	
		return Pressures;
	}
	
}
